name: Test Project
on: push
jobs: 
  test-job:
    runs-on: windows-latest
    steps:
        - name: Download the code
          uses: actions/checkout@v4

        - name: install dependencies
          uses: actions/setup-node@v4
          with:
            node-version: '20'

        - name: Install NPM packages
          run: npm ci

        - name: Run tests
          run: 'npx playwright test --grep "Test Case 1: Register User" --headed'